# encoding: UTF-8
#
# Copyright 2014, 2015 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Set to some text value if you want templated config files
# to contain a custom banner at the top of the written file
default['ibm-openstack']['zvm-driver']['custom_template_banner'] = '
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
'

# hosts
default['ibm-openstack']['zvm-driver']['hosts'] = []

# z/VM packages
default['ibm-openstack']['zvm-driver']['packages']['compute'] = ['nova-zvm-virt-driver']
default['ibm-openstack']['zvm-driver']['packages']['network'] = ['neutron-zvm-plugin']

# xcat information
# zvm_xcat_user - The xCAT REST API username.
default['ibm-openstack']['zvm-driver']['xcat']['username'] = 'admin'
# xcat_mn_admin - zvm xcat management user which allow user ssh into xcat mn
default['ibm-openstack']['zvm-driver']['xcat']['mnadmin'] = 'mnadmin'
# zvm_xcat_server - The xCAT MN IP address or host name.
default['ibm-openstack']['zvm-driver']['xcat']['server'] = ''
# zhcp_nodename - zHCP node name in xCAT.
default['ibm-openstack']['zvm-driver']['xcat']['zhcp_nodename'] = ''

# nova configuration for optimization
# The memory overcommit ratio for the z/VM Driver. The recommended value is 3.
default['ibm-openstack']['zvm-driver']['config']['ram_allocation_ratio'] = 3
# Live migration will not succeed with the default value, so set it to 180 seconds.
default['ibm-openstack']['zvm-driver']['rpc_response_timeout'] = 180

# nova configuration for z/VM compute
# The disk pool name that xCAT will allocate disk from for new servers
# Note: The zvm_diskpool name is the name of the storage 'group' defined in the Directory Manager
default['ibm-openstack']['zvm-driver']['diskpool'] = ''
# The disk pool type (can be FBA or ECKD )
default['ibm-openstack']['zvm-driver']['diskpool_type'] = ''
# The xCAT node name of the z/VM hypervisor
default['ibm-openstack']['zvm-driver']['zvm_host'] = ''
# The host is used to distinguish different nova compute host, it can be same with zvm_host
default['ibm-openstack']['zvm-driver']['host'] = ''
# Default template of user directory for new servers
# User should not use lnxdflt but should define his own profile.
default['ibm-openstack']['zvm-driver']['user_profile'] = ''
# The path that images will be stored (snapshot, deploy etc)
default['ibm-openstack']['zvm-driver']['image']['tmp_path'] = '/var/lib/nova/images'
# The xCAT master node (the node name in xCAT definition)
default['ibm-openstack']['zvm-driver']['xcat']['master'] = ''
# config_drive_format - The config driver format, should be tgz
default['ibm-openstack']['zvm-driver']['config_drive']['format'] = 'tgz'
# zvm_config_drive_inject_password
# Define whether to inject the password in config drive, if zvm_config_drive_inject_password
# is set to be True, the default os root password for the new booted vm will be the random value of
# adminPass property that is shown in the output of nova boot command.
default['ibm-openstack']['zvm-driver']['config_drive']['inject_password'] = 'False'
# Timeout value for spawn in seconds, if new spawn machine can't be reachable
# after this value, deploy will report error 'Failed to power on instance'.
default['ibm-openstack']['zvm-driver']['reachable_timeout'] = 600
# Timeout value for reading xCAT response in seconds.
default['ibm-openstack']['zvm-driver']['xcat']['connection_timeout'] = 3600
# NOT z/VM specific, set it default 86400(s) = 24hours
default['ibm-openstack']['zvm-driver']['image']['cache_manager_interval'] = 86400
# xCAT image that not used for a long time (default is 30 days) will be purged
default['ibm-openstack']['zvm-driver']['xcat']['image_clean_period'] = 30
# The threshold when xCAT MN disk space is not big enough(default is 50G), purge operation will start
default['ibm-openstack']['zvm-driver']['xcat']['free_space_threshold'] = 50
# The name of xCAT SCSI pool. Users can specify any name as their wish. xCAT will
# create and manage it.
default['ibm-openstack']['zvm-driver']['scsi_pool'] = ''
# The list of FCPs used by instances. Each instance needs one FCP in order to attach a
# volume to itself. Those FCPs should be well planned and made online before
# OpenStack can use them. OpenStack will not check their status but use them directly.
# So if they are not ready, errors may be returned. The format of this variable should look
# like 'min1-max1;min2-max2;min3-max3'. Please contact your z/VM system manager
# if you don't know what FCPs you can use.
default['ibm-openstack']['zvm-driver']['fcp_list'] = ''
# The list of FCPs used only by xCAT HCP node. It must be different to zvm_fcp_list.
# Any FCP exist in both zvm_fcp_list and zvm_zhcp_fcp_list leads to errors. The format
# of this variable should look like 'min1-max1;min2-max2;min3-max3'. Strongly
# recommend to specify only one FCP for HCP to avoid resource waste. Please contact
# your z/VM system manager if you don't know what FCPs you can use.
default['ibm-openstack']['zvm-driver']['zhcp_fcp_list'] = ''
# Live migration
# Choose one of 'ARCHITECTURE', 'DOMAIN' or 'STORAGE'
default['ibm-openstack']['zvm-driver']['vmrelocate_force'] = 'DOMAIN'

# neutron ml2 configurations
# List of network type driver entry points to be loaded with the types, separated by
# commas. z/VM supports local, flat, and vlan.
default['ibm-openstack']['zvm-driver']['ml2']['type_drivers'] = 'local,flat,vlan'
# Ordered list of network types to allocate as tenant networks, separated by commas.
# z/VM supports local, flat, and vlan.
default['ibm-openstack']['zvm-driver']['ml2']['tenant_network_types'] = 'local,flat,vlan'
# This property specifies the networking mechanism driver entry points to be loaded
# from the neutron.ml2.mechanism_drivers namespace. This value should be zvm.
default['ibm-openstack']['zvm-driver']['ml2']['mechanism_drivers'] = 'zvm'
# List of z/VM vswitch names with which flat networks can be created. Layer 2 vswitch is
# required, and then you can add other vswitches as you wish.
# Specify either the vswitch names (for example, xcatvsw2,datanet2) or use * to allow flat
# networks with arbitrary physical network names.
default['ibm-openstack']['zvm-driver']['ml2']['flat_networks'] = 'xcatvsw2'
# List of vswitch[:vlan_min:vlan_max] tuples specifying z/VM vswitch names usable for
# VLAN provider and tenant networks, each followed by the range of VLAN tags on each
# vswitch available for allocation as tenant networks (for example,
# datanet1:1:4094,datanet3:1:4094). It is optional.
default['ibm-openstack']['zvm-driver']['ml2']['network_vlan_ranges'] = ''

# neutron-zvm-agent specific
# First IP address of your management network
# Note: xCAT management interface IP address. xCAT uses this IP address to connect a
# newly-deployed instance server.
default['ibm-openstack']['zvm-driver']['xcat']['mgt_ip'] = ''
# Netmask of your management network
# Note: xCAT management interface netmask, for example: 255.255.255.0
default['ibm-openstack']['zvm-driver']['xcat']['mgt_mask'] = ''
# Neutron zvm agent's polling interval, in seconds.
# Depends on network and workload
default['ibm-openstack']['zvm-driver']['polling_interval'] = 5
# The number of seconds the agent will wait for xCAT MN response.
# Recommended Value: 300
default['ibm-openstack']['zvm-driver']['xcat']['timeout'] = 300
# OSA configuration for each of the vswitches,
# these configurations are required if vswitch needs to connect outside of z/VM. The format of
# this variable should look like 'datanet1:6243,6245;datanet3:6343'. The datanet1 and datanet3 are
# vswitches, The 6243, 6245, 6343 are RDEV address of the OSA cards which are connected to the vswitch.
default['ibm-openstack']['zvm-driver']['external_vswitch_mappings'] = ''
